# @package _global_

resize_shape: null
crop_shape: [76, 76]

task:
  name: robomimic_transport

  image_keys:
    - observation.images.agentview
    - observation.images.wrist_left
    - observation.images.wrist_right
  state_key: observation.state
  action_key: action
  state_dim: 18     # (3 + 4 + 2) x 2팔
  fps: 20
  action_dim: 14

  hdf5_path: ${oc.env:MANIBOT_DATASETS_DIR,data}/transport/ph/transport_image_v15.hdf5
  dataset_repo_id: null
  dataset_root: ${oc.env:MANIBOT_DATASETS_DIR,data}/robomimic_transport

  sim:
    backend: robosuite
    env_name: TwoArmTransport
    robots: [Panda, Panda]
    image_size: 84
    max_steps: 700   # 에피소드 최대 스텝 (rollout 평가)
    gripper_types: null
    state_from:
      - robot0_eef_pos
      - robot0_eef_quat
      - robot0_gripper_qpos
      - robot1_eef_pos
      - robot1_eef_quat
      - robot1_gripper_qpos
    cameras:
      agentview: observation.images.agentview
      robot0_eye_in_hand: observation.images.wrist_left
      robot1_eye_in_hand: observation.images.wrist_right
    env_kwargs:
      env_configuration: single-arm-opposed
      lite_physics: false
      controller_configs:
        type: BASIC
        body_parts:
          right:
            type: OSC_POSE
            input_max: 1
            input_min: -1
            output_max: [0.05, 0.05, 0.05, 0.5, 0.5, 0.5]
            output_min: [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5]
            kp: 150
            damping: 1
            impedance_mode: fixed
            kp_limits: [0, 300]
            damping_limits: [0, 10]
            position_limits: null
            orientation_limits: null
            uncouple_pos_ori: true
            control_delta: true
            interpolation: null
            ramp_ratio: 0.2
            input_ref_frame: world
            gripper:
              type: GRIP
